### ISSUE TITLE
h2o R Package: Cheatsheet

### ISSUE THREAD

**Issue by jtelleria** [h2oai/h2o-tutorials#52]
I would like to propose that a new cheatsheet is created for h2o R Package, understood as a concept summary for using h2o with R:

https://cran.r-project.org/web/packages/h2o/index.html

The template can be found in the following webpage:
https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/

Then, the cheatsheet could be distributed through RStudio Cheatsheet webpage, in the "Contributed Cheatsheets" Section:
https://www.rstudio.com/resources/cheatsheets/

**Comment by jtelleria** [comment]
I consider this cheatsheet very import because:
- It would help to spread the word about h2o in the R Community, as most R users use RStudio.
- It is important to have concepts clear and summarized.

**Comment by jphall663** [comment]
We have this: https://github.com/h2oai/h2o-tutorials/blob/master/training/h2o_algos/h2o_algos_cheat_sheet_04_25_17.pdf

Is there any appetite for adding R and/or Python Snippets to go along with current graphics and pointers?

**Comment by jtelleriar** [comment]
I was thinking more of h2o R package key function summary, such as the ones you can find in: 
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/booklets/RBooklet.pdf
https://h2o-release.s3.amazonaws.com/h2o/rel-slater/9/docs-website/h2o-docs/booklets/DeepLearning_Vignette.pdf

@jphall663 The cheatsheet you mentioned explains the concepts on when too use one model or another. It's complement would be a cheatsheet that explains the functions to user for each modeling technique.

I could help myself in such development.

Juan

**Comment by jtelleria** [comment]
I started to do the h2o R Command Cheatsheet by myself.
If anyone is interested in collaboration, I attach to this comment what I have done till now.
[H2O Cheatsheet v1.04.pptx](https://github.com/h2oai/h2o-tutorials/files/1691839/H2O.Cheatsheet.v1.04.pptx)

In addition, I have also uploaded the PowerPoint to my R Github account:
https://github.com/jtelleria/H2O-Cheatsheet

**Comment by ledell** [comment]
@jtelleria Are you interested in converting your cheatsheet into the RStudio template?  That would be very nice!

**Comment by jtelleria** [comment]
Yes, indeed, you can check out what I've done till now here:
https://github.com/jtelleria/H2O-Cheatsheet

Juan

**Comment by jtelleria** [comment]
I have already finished editing the h2o R Front-End Cheatsheet:

PDF:
https://github.com/jtelleria/H2O-Cheatsheet/blob/master/H2O%20Cheatsheet%20v2.000.pdf

POWER POINT:
https://github.com/jtelleria/H2O-Cheatsheet/blob/master/H2O%20Cheatsheet%20v2.000.pptx

I will give the final touches next week and submit it to the RStudio Cheatsheet webpage:

https://www.rstudio.com/resources/cheatsheets/

Contribution to polish final details is always welcome.

Kind regards,
Juan Telleria

**Comment by jphall663** [comment]
looks awesome - @ledell have a look!

**Comment by ledell** [comment]
Hi @jtelleria, I am just seeing this now.  Thanks for the contribution!  There are a few things that we'd like like to edit; here are some things I noticed at first glace:

pg1
- clarify the difference between how `h2o.importFile()` and `h2o.uploadFile()` work
- clarify the difference between how `h2o.exportFile()` and `h2o.downloadCSV()` work 
- remove `colnames()` as it's a duplicate of `names()`

It would be nice to add two new functions for "data generation", `h2o.target_encode_apply` and `h2o.target_encode_apply()`.

pg2
- typo in `h2o.group_by()` its missing the underscore
- add `h2o.revel()` and `h2o.setLevels()` to "factor level manipulations"
- date manipulations section is missing the rest of the ops, like `h2o.day()`, `h2o.month()`, `h2o.hour()`, `h2o.dayOfWeek()`
- supervised learning section is missing: `h2o.stackedEnsemble()` and `h2o.automl()`
- unsupervised modeling section is missing: `h2o.glrm()` and `h2o.svd()` and could also include `h2o.word2vec()`.
- add `h2o.getGrid()`
- remove (also typo): `ho2.model metrics` this does not exist... i think you make `h2o.make_metrics()`
- `h2o.performance()` should not be in` Classification model helpers" -- this works for any type of model
- would be nice to show how to get the train, valid and xval metrics from H2O models using `h2o.somemetric(model, xval = TRUE)` for example.
- add `h2o.scoringHistory()` near modeling functions
- add `h2o.varimp` and `h2o.varimp_plot()`.
- add `h2o.removeAll()` to cluster operations
- it's missing `h2o.download_pojo()` and `h2o.download_mojo()` which are important because it's how you productionize H2O models.  maybe you could change "h2o object serialization" section to "h2o model import/export" and put all of these there.
- you don't need to specify `nfolds = -1` in `h2o.init()` because that's the default.  I'd also remove load balancing to the bottom of the column or remove. i don't think anyone ever uses this.

I think we should probably add `h2o.merge()`, `h2o.rbind()` and `h2o.cbind()` and `h2o.arrange()` (sorting) under the data munging section.  If there is a way where we can show how to slice rows and columns, that would also be good.  All data munging ops are here: 
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-munging.html

Overall, I think there could be more of an emphasis on the machine learning and less of an emphasis on the basic math operations, but this is a great start!  Probably to add some of the things I recommended, it will require you to remove some less essential things (maybe from the front page).

**Comment by jtelleriar** [comment]
Great, thank you.

I'll implement for sure such changes. The major issue I had was a problem
of space, in order to be able to fit all important functions into a single
sheet. Will think of a turnaround and:
* Re-organize.
* Prioritize.
* Re-define.
Those key concepts.

I would also like to do more Cheatsheets for key H2O.ai algos for R, with:
* Key Function Arguments.
* Hyperparameter tunning generic examples and rule of thumb tips.
* Algorithm Generic Concepts, based on:

https://github.com/h2oai/h2o-tutorials/raw/master/training/h2o_algos/h2o_algos_cheat_sheet_04_25_17.pdf

But will take me some time.

Best,
Juan

**Comment by jtelleria** [comment]
@ledell I started implementing little by little the checklist you included above:
https://github.com/jtelleria/H2O-Cheatsheet/blob/master/H2O%20Cheatsheet%20v2.018.pptx

However, I have 2 doubts with "Methods from Group Generics":
* In h2o R package documentation for MATH(H2O), we cannot see, for example, abs() function, only h2o.abs(). If we call the first over an H2O Parsed Data Frame, would we be invoking the second for being a Group Generic?
* All these "Group Generic Functions" (MATH, MATH2, etc) are vectorized? Or shall be used with apply?

Thank you,
Juan

**Comment by ledell** [comment]
@jtelleria 

- You're right, we don't have those functions properly documented.  The only way to get to them is through the `h2o.abs()` version. The functions are identical (and are aliases of each other) so it doesn't matter which one you call in your code.   I made a [ticket](https://0xdata.atlassian.net/browse/PUBDEV-5607) to update the docs.
- Yes and they can be used with apply on H2OFrames.

**Comment by jtelleria** [comment]
@ledell I noticed that function count() does not exists, but it is documented as if it existed:

https://h2o-release.s3.amazonaws.com/h2o/rel-vajda/1/docs-website/h2o-docs/data-munging/groupby.html

Instead, H2O users shall use nrow():
```
h2o.group_by(data = starwars, by = "skin_color", nrow("skin_color"), gb.control=list(na.methods="rm"))
```
I also noticed that with h2o.group_by() we cannot use the full name of some summary functions, and we shall use instead their "Group Generic" Version. E.g.: Use sum() instead of h2o.sum()

I do think however that it is a good coding practice to use functions named as h2o.*, for emphasizing that we are working over a "H2O Parsed Data Object" explicitly (Even if that occurs through Methods).

**Comment by jtelleria** [comment]
Created an Issue on JIRA:
https://0xdata.atlassian.net/browse/PUBDEV-5627

Thank you.
Juan

**Comment by jtelleria** [comment]
I have just finished the Second Version of the H2O Cheatsheet with all the changes you commented me.

You can download it here, in case you want to do any final suggestions before I do a pull request to RStudio Cheatsheet Repository:

https://github.com/jtelleria/H2O-Cheatsheet/raw/master/h2o.pdf

Best,
Juan

**Comment by jtelleria** [comment]
Done the Pull Request, the updated Cheatsheet can be downloaded at:

https://www.rstudio.com/resources/cheatsheets/
